services:

  medplum:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    ports:
      - '3000:3000'
      - '8103:8103'
    volumes:
      - ./medplum/medplum.config.json:/workspace/packages/server/medplum.config.json

  postgres:
    image: postgres:12-bullseye
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/load_extensions.sql:/docker-entrypoint-initdb.d/load_extensions.sql

  redis:
    image: redis:6-bullseye
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'

volumes:
  postgres_data: